'use client';

import { useState } from 'react';
import GeneratedByGpt from '@/components/GeneratedByGpt';
import ImprovedByGrok from '@/components/ImprovedByGrok';
import ImprovedByHuman from '@/components/ImprovedByHuman';

enum ACTIVE_FORM {
  GENERATED_BY_AI = 'generated by AI',
  IMPROVED_BY_AI = 'improved by AI',
  HUMAN = 'HUMAN',
}

const MainComponent = () => {
  const [activeForm, setActiveForm] = useState<ACTIVE_FORM | null>(null);

  const options = [
    { text: 'Generated by AI', activation: ACTIVE_FORM.GENERATED_BY_AI },
    { text: 'Improved by AI', activation: ACTIVE_FORM.IMPROVED_BY_AI },
    { text: 'Improved by Human', activation: ACTIVE_FORM.HUMAN },
  ];

  const handleOptionClick = (value: ACTIVE_FORM) => {
    setActiveForm(value);
  };

  return (
    <div className={'flex flex-col items-center gap-3 w-full'}>
      <h2 className={'text-center text-3xl'}>Activate a version</h2>
      <div className={'flex gap-2'}>
        {options.map((option) => (
          <button
            onClick={() => handleOptionClick(option.activation)}
            className={`${activeForm === option.activation ? 'bg-amber-500' : ''} bg-amber-400 px-3 py-1 rounded-sm cursor-pointer hover:bg-amber-500 active:bg-amber-600 shadow outline-none`}
            key={option.text}
          >
            {option.text}
          </button>
        ))}
      </div>
      <div className={'mt-[150px] w-full'}>
        <div className={'grid grid-cols-3 gap-2'}>
          <div className={'flex items-center max-w-sm'}>
            <GeneratedByGpt
              isActive={activeForm === ACTIVE_FORM.GENERATED_BY_AI}
            />
          </div>

          <div className={'flex items-center max-w-sm'}>
            <ImprovedByGrok
              isActive={activeForm === ACTIVE_FORM.IMPROVED_BY_AI}
            />
          </div>

          <div className={'flex items-center max-w-sm'}>
            <ImprovedByHuman isActive={activeForm === ACTIVE_FORM.HUMAN} />
          </div>
        </div>
      </div>
    </div>
  );
};

export default MainComponent;
