'use client';

import { useState } from 'react';
import GeneratedByGpt from '@/components/GeneratedByGpt';
import ImprovedByGrok from '@/components/ImprovedByGrok';
import ImprovedByHuman from '@/components/ImprovedByHuman';
import { activeFormOptions } from '@/constants';

const MainComponent = () => {
  const [activeForm, setActiveForm] = useState<string | null>(null);

  const options = [
    { text: 'Generated by AI', activation: activeFormOptions.generatedByAi },
    { text: 'Improved by AI', activation: activeFormOptions.improvedByAi },
    { text: 'Improved by Human', activation: activeFormOptions.human },
  ];

  const handleOptionClick = (value: string) => {
    setActiveForm(value);
  };

  return (
    <div className={'flex flex-col items-center gap-3 w-full'}>
      <h2 className={'text-center text-3xl'}>Activate a version</h2>
      <div className={'flex gap-2'}>
        {options.map((option) => (
          <button
            onClick={() => handleOptionClick(option.activation)}
            className={`${activeForm === option.activation ? 'bg-amber-500' : ''} bg-amber-400 px-3 py-1 rounded-sm cursor-pointer hover:bg-amber-500 active:bg-amber-600 shadow outline-none`}
            key={option.text}
          >
            {option.text}
          </button>
        ))}
      </div>
      <div className={'mt-[150px] w-full'}>
        <div className={'grid grid-cols-3 gap-2'}>
          <div className={'flex items-center max-w-sm'}>
            <GeneratedByGpt
              isActive={activeForm === activeFormOptions.generatedByAi}
            />
          </div>

          <div className={'flex items-center max-w-sm'}>
            <ImprovedByGrok
              isActive={activeForm === activeFormOptions.improvedByAi}
            />
          </div>

          <div className={'flex items-center max-w-sm'}>
            <ImprovedByHuman
              isActive={activeForm === activeFormOptions.human}
            />
          </div>
        </div>
      </div>
    </div>
  );
};

export default MainComponent;
