export const validationStatusObj = {
  valid: 'valid',
  notProvided: "Please enter a contestant's last name.",
  tooShort: 'Name is too short.',
  includesNumbers: 'Name cannot include numbers.',
};

export const activeFormOptions = {
  generatedByAi: 'generated by AI',
  improvedByAi: 'improved by AI',
  human: 'human',
};

export const CONTAINS_NUMBER_REGEXP = /\d/;
export const MIN_MESSAGE_LENGTH = 3;
